enum KeyCode {
  number0(label: '0 key', code: 'KEYCODE_0'),
  number1(label: '1 key', code: 'KEYCODE_1'),
  number2(label: '2 key', code: 'KEYCODE_2'),
  number3(label: '3 key', code: 'KEYCODE_3'),
  mode3D(label: '3D Mode key', code: 'KEYCODE_3D_MODE'),
  number4(label: '4 key', code: 'KEYCODE_4'),
  number5(label: '5 key', code: 'KEYCODE_5'),
  number6(label: '6 key', code: 'KEYCODE_6'),
  number7(label: '7 key', code: 'KEYCODE_7'),
  number8(label: '8 key', code: 'KEYCODE_8'),
  number9(label: '9 key', code: 'KEYCODE_9'),
  letterA(label: 'A key', code: 'KEYCODE_A'),
  buttonA(label: 'A Button key', code: 'KEYCODE_BUTTON_A'),
  tvTerrestrialAnalog(
    label: 'Analog Terrestrial key',
    code: 'KEYCODE_TV_TERRESTRIAL_ANALOG',
  ),
  tvAntennaCable(label: 'Antenna/Cable key', code: 'KEYCODE_TV_ANTENNA_CABLE'),
  appSwitch(label: 'App switch key', code: 'KEYCODE_APP_SWITCH'),
  assist(label: 'Assist key', code: 'KEYCODE_ASSIST'),
  audioDescription(
    label: 'Audio description key',
    code: 'KEYCODE_TV_AUDIO_DESCRIPTION',
  ),
  tvAudioDescriptionMixDown(
    label: 'Audio description mixing volume down key',
    code: 'KEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN',
  ),
  tvAudioDescriptionMixUp(
    label: 'Audio description mixing volume up key',
    code: 'KEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP',
  ),
  mediaAudioTrack(label: 'Audio Track key', code: 'KEYCODE_MEDIA_AUDIO_TRACK'),
  avrInput(label: 'A/V Receiver input key', code: 'KEYCODE_AVR_INPUT'),
  avrPower(label: 'A/V Receiver power key', code: 'KEYCODE_AVR_POWER'),
  letterB(label: 'B key', code: 'KEYCODE_B'),
  buttonB(label: 'B Button key', code: 'KEYCODE_BUTTON_B'),
  back(label: 'Back key', code: 'KEYCODE_BACK'),
  backspace(label: 'Backspace key', code: 'KEYCODE_DEL'),
  programmableBlue(
      label: 'Blue \'programmable\' key', code: 'KEYCODE_PROG_BLUE'),
  bookmark(label: 'Bookmark key', code: 'KEYCODE_BOOKMARK'),
  breakPause(label: 'Break / Pause key', code: 'KEYCODE_BREAK'),
  brightnessDown(label: 'Brightness Down key', code: 'KEYCODE_BRIGHTNESS_DOWN'),
  brightnessUp(label: 'Brightness Up key', code: 'KEYCODE_BRIGHTNESS_UP'),
  tvSatelliteBs(label: 'BS key', code: 'KEYCODE_TV_SATELLITE_BS'),
  tvSatelliteService(label: 'BS/CS key', code: 'KEYCODE_TV_SATELLITE_SERVICE'),
  letterC(label: 'C key', code: 'KEYCODE_C'),
  buttonC(label: 'C Button key', code: 'KEYCODE_BUTTON_C'),
  calculator(
    label: 'Calculator special function key',
    code: 'KEYCODE_CALCULATOR',
  ),
  calendar(label: 'Calendar special function key', code: 'KEYCODE_CALENDAR'),
  call(label: 'Call key', code: 'KEYCODE_CALL'),
  camera(label: 'Camera key', code: 'KEYCODE_CAMERA'),
  focus(label: 'Camera Focus key', code: 'KEYCODE_FOCUS'),
  capsLock(label: 'Caps Lock key', code: 'KEYCODE_CAPS_LOCK'),
  channelDown(label: 'Channel down key', code: 'KEYCODE_CHANNEL_DOWN'),
  channelUp(label: 'Channel up key', code: 'KEYCODE_CHANNEL_UP'),
  clear(label: 'Clear key', code: 'KEYCODE_CLEAR'),
  mediaClose(label: 'Close media key', code: 'KEYCODE_MEDIA_CLOSE'),
  tvComponent1(label: 'Component #1 key', code: 'KEYCODE_TV_INPUT_COMPONENT_1'),
  tvComponent2(label: 'Component #2 key', code: 'KEYCODE_TV_INPUT_COMPONENT_2'),
  tvComposite1(label: 'Composite #1 key', code: 'KEYCODE_TV_INPUT_COMPOSITE_1'),
  tvComposite2(label: 'Composite #2 key', code: 'KEYCODE_TV_INPUT_COMPOSITE_2'),
  contacts(label: 'Contacts special function key', code: 'KEYCODE_CONTACTS'),
  tvContentsMenu(label: 'Contents menu key', code: 'KEYCODE_TV_CONTENTS_MENU'),
  copy(label: 'Copy key', code: 'KEYCODE_COPY'),
  satelliteCs(label: 'CS key', code: 'KEYCODE_TV_SATELLITE_CS'),
  cut(label: 'Cut key', code: 'KEYCODE_CUT'),
  letterD(label: 'D key', code: 'KEYCODE_D'),
  tvTerrestrialDigital(
    label: 'Digital Terrestrial key',
    code: 'KEYCODE_TV_TERRESTRIAL_DIGITAL',
  ),
  dpadCenter(label: 'Directional Pad Center key', code: 'KEYCODE_DPAD_CENTER'),
  dpadDown(label: 'Directional Pad Down key', code: 'KEYCODE_DPAD_DOWN'),
  dpadDownLeft(
    label: 'Directional Pad Down-Left key',
    code: 'KEYCODE_DPAD_DOWN_LEFT',
  ),
  dpadDownRight(
    label: 'Directional Pad Down-Right key',
    code: 'KEYCODE_DPAD_DOWN_RIGHT',
  ),
  dpadLeft(label: 'Directional Pad Left key', code: 'KEYCODE_DPAD_LEFT'),
  dpadRight(label: 'Directional Pad Right key', code: 'KEYCODE_DPAD_RIGHT'),
  dpadUp(label: 'Directional Pad Up key', code: 'KEYCODE_DPAD_UP'),
  dpadUpLeft(
    label: 'Directional Pad Up-Left key',
    code: 'KEYCODE_DPAD_UP_LEFT',
  ),
  dpadUpRight(
    label: 'Directional Pad Up-Right key',
    code: 'KEYCODE_DPAD_UP_RIGHT',
  ),
  dvr(label: 'DVR key', code: 'KEYCODE_DVR'),
  letterE(label: 'E key', code: 'KEYCODE_E'),
  mediaEject(label: 'Eject media key', code: 'KEYCODE_MEDIA_EJECT'),
  endCall(label: 'End Call key', code: 'KEYCODE_ENDCALL'),
  moveEnd(label: 'End Movement key', code: 'KEYCODE_MOVE_END'),
  enter(label: 'Enter key', code: 'KEYCODE_ENTER'),
  envelope(label: 'Envelope special function key', code: 'KEYCODE_ENVELOPE'),
  escape(label: 'Escape key', code: 'KEYCODE_ESCAPE'),
  explorer(label: 'Explorer special function key', code: 'KEYCODE_EXPLORER'),
  letterF(label: 'F key', code: 'KEYCODE_F'),
  mediaFastForward(
    label: 'Fast Forward media key',
    code: 'KEYCODE_MEDIA_FAST_FORWARD',
  ),
  forward(label: 'Forward key', code: 'KEYCODE_FORWARD'),
  forwardDelete(label: 'Forward Delete key', code: 'KEYCODE_FORWARD_DEL'),
  function(label: 'Function key', code: 'KEYCODE_FUNCTION'),
  f1(label: 'F1 key', code: 'KEYCODE_F1'),
  f10(label: 'F10 key', code: 'KEYCODE_F10'),
  f11(label: 'F11 key', code: 'KEYCODE_F11'),
  f12(label: 'F12 key', code: 'KEYCODE_F12'),
  f2(label: 'F2 key', code: 'KEYCODE_F2'),
  f3(label: 'F3 key', code: 'KEYCODE_F3'),
  f4(label: 'F4 key', code: 'KEYCODE_F4'),
  f5(label: 'F5 key', code: 'KEYCODE_F5'),
  f6(label: 'F6 key', code: 'KEYCODE_F6'),
  f7(label: 'F7 key', code: 'KEYCODE_F7'),
  f8(label: 'F8 key', code: 'KEYCODE_F8'),
  f9(label: 'F9 key', code: 'KEYCODE_F9'),
  letterG(label: 'G key', code: 'KEYCODE_G'),
  gamePad1(label: 'Generic Game Pad Button #1', code: 'KEYCODE_BUTTON_1'),
  gamePad10(label: 'Generic Game Pad Button #10', code: 'KEYCODE_BUTTON_10'),
  gamePad11(label: 'Generic Game Pad Button #11', code: 'KEYCODE_BUTTON_11'),
  gamePad12(label: 'Generic Game Pad Button #12', code: 'KEYCODE_BUTTON_12'),
  gamePad13(label: 'Generic Game Pad Button #13', code: 'KEYCODE_BUTTON_13'),
  gamePad14(label: 'Generic Game Pad Button #14', code: 'KEYCODE_BUTTON_14'),
  gamePad15(label: 'Generic Game Pad Button #15', code: 'KEYCODE_BUTTON_15'),
  gamePad16(label: 'Generic Game Pad Button #16', code: 'KEYCODE_BUTTON_16'),
  gamePad2(label: 'Generic Game Pad Button #2', code: 'KEYCODE_BUTTON_2'),
  gamePad3(label: 'Generic Game Pad Button #3', code: 'KEYCODE_BUTTON_3'),
  gamePad4(label: 'Generic Game Pad Button #4', code: 'KEYCODE_BUTTON_4'),
  gamePad5(label: 'Generic Game Pad Button #5', code: 'KEYCODE_BUTTON_5'),
  gamePad6(label: 'Generic Game Pad Button #6', code: 'KEYCODE_BUTTON_6'),
  gamePad7(label: 'Generic Game Pad Button #7', code: 'KEYCODE_BUTTON_7'),
  gamePad8(label: 'Generic Game Pad Button #8', code: 'KEYCODE_BUTTON_8'),
  gamePad9(label: 'Generic Game Pad Button #9', code: 'KEYCODE_BUTTON_9'),
  stem1(label: 'Generic stem key 1 for Wear', code: 'KEYCODE_STEM_1'),
  stem2(label: 'Generic stem key 2 for Wear', code: 'KEYCODE_STEM_2'),
  stem3(label: 'Generic stem key 3 for Wear', code: 'KEYCODE_STEM_3'),
  programmableGreen(
    label: 'Green \'programmable\' key',
    code: 'KEYCODE_PROG_GREEN',
  ),
  guide(label: 'Guide key', code: 'KEYCODE_GUIDE'),
  letterH(label: 'H key', code: 'KEYCODE_H'),
  tvHdmi1(label: 'HDMI #1 key', code: 'KEYCODE_TV_INPUT_HDMI_1'),
  tvHdmi2(label: 'HDMI #2 key', code: 'KEYCODE_TV_INPUT_HDMI_2'),
  tvHdmi3(label: 'HDMI #3 key', code: 'KEYCODE_TV_INPUT_HDMI_3'),
  tvHdmi4(label: 'HDMI #4 key', code: 'KEYCODE_TV_INPUT_HDMI_4'),
  headsetHook(label: 'Headset Hook key', code: 'KEYCODE_HEADSETHOOK'),
  help(label: 'Help key', code: 'KEYCODE_HELP'),
  home(label: 'Home key', code: 'KEYCODE_HOME'),
  moveHome(label: 'Home Movement key', code: 'KEYCODE_MOVE_HOME'),
  letterI(label: 'I key', code: 'KEYCODE_I'),
  info(label: 'Info key', code: 'KEYCODE_INFO'),
  insert(label: 'Insert key', code: 'KEYCODE_INSERT'),
  letterJ(label: 'J key', code: 'KEYCODE_J'),
  japaneseAlphanumeric(
      label: 'Japanese alphanumeric key', code: 'KEYCODE_EISU'),
  japaneseConversion(
    label: 'Japanese conversion key',
    code: 'KEYCODE_HENKAN',
  ),
  japaneseWidth(
    label: 'Japanese full-width / half-width key',
    code: 'KEYCODE_ZENKAKU_HANKAKU',
  ),
  japaneseKana(label: 'Japanese kana key', code: 'KEYCODE_KANA'),
  japaneseKatakana(
    label: 'Japanese katakana / hiragana key',
    code: 'KEYCODE_KATAKANA_HIRAGANA',
  ),
  japaneseNonConversion(
    label: 'Japanese non-conversion key',
    code: 'KEYCODE_MUHENKAN',
  ),
  japaneseRo(label: 'Japanese Ro key', code: 'KEYCODE_RO'),
  japaneseYen(label: 'Japanese Yen key', code: 'KEYCODE_YEN'),
  letterK(label: 'K key', code: 'KEYCODE_K'),
  letterL(label: 'L key', code: 'KEYCODE_L'),
  languageSwitch(label: 'Language Switch key', code: 'KEYCODE_LANGUAGE_SWITCH'),
  lastChannel(label: 'Last Channel key', code: 'KEYCODE_LAST_CHANNEL'),
  buttonL1(label: 'L1 Button key', code: 'KEYCODE_BUTTON_L1'),
  buttonL2(label: 'L2 Button key', code: 'KEYCODE_BUTTON_L2'),
  altLeft(label: 'Left Alt modifier key', code: 'KEYCODE_ALT_LEFT'),
  controlLeft(label: 'Left Control modifier key', code: 'KEYCODE_CTRL_LEFT'),
  metaLeft(label: 'Left Meta modifier key', code: 'KEYCODE_META_LEFT'),
  shiftLeft(label: 'Left Shift modifier key', code: 'KEYCODE_SHIFT_LEFT'),
  thumbLeft(label: 'Left Thumb Button key', code: 'KEYCODE_BUTTON_THUMBL'),
  letterM(label: 'M key', code: 'KEYCODE_M'),
  mannerMode(label: 'Manner Mode key', code: 'KEYCODE_MANNER_MODE'),
  mode(label: 'Mode Button key', code: 'KEYCODE_BUTTON_MODE'),
  tvMediaContextMenu(
    label: 'Media context menu key',
    code: 'KEYCODE_TV_MEDIA_CONTEXT_MENU',
  ),
  mediaTopMenu(label: 'Media Top Menu key', code: 'KEYCODE_MEDIA_TOP_MENU'),
  menu(label: 'Menu key', code: 'KEYCODE_MENU'),
  music(label: 'Music special function key', code: 'KEYCODE_MUSIC'),
  mute(label: 'Mute key', code: 'KEYCODE_MUTE'),
  letterN(label: 'N key', code: 'KEYCODE_N'),
  navigateIn(label: 'Navigate in key', code: 'KEYCODE_NAVIGATE_IN'),
  navigateOut(label: 'Navigate out key', code: 'KEYCODE_NAVIGATE_OUT'),
  navigateNext(label: 'Navigate to next key', code: 'KEYCODE_NAVIGATE_NEXT'),
  navigatePrevious(
    label: 'Navigate to previous key',
    code: 'KEYCODE_NAVIGATE_PREVIOUS',
  ),
  notification(label: 'Notification key', code: 'KEYCODE_NOTIFICATION'),
  tvNumberEntry(label: 'Number entry key', code: 'KEYCODE_TV_NUMBER_ENTRY'),
  num(label: 'Number modifier key', code: 'KEYCODE_NUM'),
  numpadEnter(label: 'Numeric keypad Enter key', code: 'KEYCODE_NUMPAD_ENTER'),
  numpad0(label: 'Numeric keypad 0 key', code: 'KEYCODE_NUMPAD_0'),
  numpad1(label: 'Numeric keypad 1 key', code: 'KEYCODE_NUMPAD_1'),
  numpad2(label: 'Numeric keypad 2 key', code: 'KEYCODE_NUMPAD_2'),
  numpad3(label: 'Numeric keypad 3 key', code: 'KEYCODE_NUMPAD_3'),
  numpad4(label: 'Numeric keypad 4 key', code: 'KEYCODE_NUMPAD_4'),
  numpad5(label: 'Numeric keypad 5 key', code: 'KEYCODE_NUMPAD_5'),
  numpad6(label: 'Numeric keypad 6 key', code: 'KEYCODE_NUMPAD_6'),
  numpad7(label: 'Numeric keypad 7 key', code: 'KEYCODE_NUMPAD_7'),
  numpad8(label: 'Numeric keypad 8 key', code: 'KEYCODE_NUMPAD_8'),
  numpad9(label: 'Numeric keypad 9 key', code: 'KEYCODE_NUMPAD_9'),
  numpadAdd(label: 'Numeric keypad + key', code: 'KEYCODE_NUMPAD_ADD'),
  numpadComma(label: 'Numeric keypad , key', code: 'KEYCODE_NUMPAD_COMMA'),
  numpadDivide(label: 'Numeric keypad / key', code: 'KEYCODE_NUMPAD_DIVIDE'),
  numpadDot(label: 'Numeric keypad . key', code: 'KEYCODE_NUMPAD_DOT'),
  numpadEquals(label: 'Numeric keypad = key', code: 'KEYCODE_NUMPAD_EQUALS'),
  numpadParenthesisLeft(
    label: 'Numeric keypad ( key',
    code: 'KEYCODE_NUMPAD_LEFT_PAREN',
  ),
  numpadMultiply(
    label: 'Numeric keypad * key',
    code: 'KEYCODE_NUMPAD_MULTIPLY',
  ),
  numpadParenthesisRight(
    label: 'Numeric keypad ) key',
    code: 'KEYCODE_NUMPAD_RIGHT_PAREN',
  ),
  numpadSubtract(
    label: 'Numeric keypad - key',
    code: 'KEYCODE_NUMPAD_SUBTRACT',
  ),
  numLock(label: 'Num Lock key', code: 'KEYCODE_NUM_LOCK'),
  letterO(label: 'O key', code: 'KEYCODE_O'),
  letterP(label: 'P key', code: 'KEYCODE_P'),
  pageDown(label: 'Page Down key', code: 'KEYCODE_PAGE_DOWN'),
  pageUp(label: 'Page Up key', code: 'KEYCODE_PAGE_UP'),
  pairing(label: 'Pairing key', code: 'KEYCODE_PAIRING'),
  paste(label: 'Paste key', code: 'KEYCODE_PASTE'),
  mediaPause(label: 'Pause media key', code: 'KEYCODE_MEDIA_PAUSE'),
  pictureSymbols(
    label: 'Picture Symbols modifier key',
    code: 'KEYCODE_PICTSYMBOLS',
  ),
  mediaPlay(label: 'Play media key', code: 'KEYCODE_MEDIA_PLAY'),
  mediaNext(label: 'Play Next media key', code: 'KEYCODE_MEDIA_NEXT'),
  mediaPrevious(
    label: 'Play Previous media key',
    code: 'KEYCODE_MEDIA_PREVIOUS',
  ),
  mediaPlayPause(
    label: 'Play/Pause media key',
    code: 'KEYCODE_MEDIA_PLAY_PAUSE',
  ),
  power(label: 'Power key', code: 'KEYCODE_POWER'),
  stemPrimary(label: 'Primary stem key for Wear', code: 'KEYCODE_STEM_PRIMARY'),
  profileSwitch(label: 'Profile Switch key', code: 'KEYCODE_PROFILE_SWITCH'),
  letterQ(label: 'Q key', code: 'KEYCODE_Q'),
  letterR(label: 'R key', code: 'KEYCODE_R'),
  tvRadioService(label: 'Radio key', code: 'KEYCODE_TV_RADIO_SERVICE'),
  mediaRecord(label: 'Record media key', code: 'KEYCODE_MEDIA_RECORD'),
  programmableRed(label: 'Red \'programmable\' key', code: 'KEYCODE_PROG_RED'),
  refresh(label: 'Refresh key', code: 'KEYCODE_REFRESH'),
  mediaRewind(label: 'Rewind media key', code: 'KEYCODE_MEDIA_REWIND'),
  altRight(label: 'Right Alt modifier key', code: 'KEYCODE_ALT_RIGHT'),
  controlRight(label: 'Right Control modifier key', code: 'KEYCODE_CTRL_RIGHT'),
  metaRight(label: 'Right Meta modifier key', code: 'KEYCODE_META_RIGHT'),
  shiftRight(label: 'Right Shift modifier key', code: 'KEYCODE_SHIFT_RIGHT'),
  thumbRight(label: 'Right Thumb Button key', code: 'KEYCODE_BUTTON_THUMBR'),
  buttonR1(label: 'R1 Button key', code: 'KEYCODE_BUTTON_R1'),
  buttonR2(label: 'R2 Button key', code: 'KEYCODE_BUTTON_R2'),
  letterS(label: 'S key', code: 'KEYCODE_S'),
  tvSatellite(label: 'Satellite key', code: 'KEYCODE_TV_SATELLITE'),
  scrollLock(label: 'Scroll Lock key', code: 'KEYCODE_SCROLL_LOCK'),
  search(label: 'Search key', code: 'KEYCODE_SEARCH'),
  buttonSelect(label: 'Select Button key', code: 'KEYCODE_BUTTON_SELECT'),
  settings(label: 'Settings key', code: 'KEYCODE_SETTINGS'),
  stbInput(label: 'Set-top-box input key', code: 'KEYCODE_STB_INPUT'),
  stbPower(label: 'Set-top-box power key', code: 'KEYCODE_STB_POWER'),
  allApps(label: 'Show all apps', code: 'KEYCODE_ALL_APPS'),
  mediaSkipBackward(
    label: 'Skip backward media key',
    code: 'KEYCODE_MEDIA_SKIP_BACKWARD',
  ),
  mediaSkipForward(
    label: 'Skip forward media key',
    code: 'KEYCODE_MEDIA_SKIP_FORWARD',
  ),
  sleep(label: 'Sleep key', code: 'KEYCODE_SLEEP'),
  softLeft(label: 'Soft Left key', code: 'KEYCODE_SOFT_LEFT'),
  softRight(label: 'Soft Right key', code: 'KEYCODE_SOFT_RIGHT'),
  softSleep(label: 'Soft Sleep key', code: 'KEYCODE_SOFT_SLEEP'),
  space(label: 'Space key', code: 'KEYCODE_SPACE'),
  buttonStart(label: 'Start Button key', code: 'KEYCODE_BUTTON_START'),
  mediaStepBackward(
    label: 'Step backward media key',
    code: 'KEYCODE_MEDIA_STEP_BACKWARD',
  ),
  mediaStepForward(
    label: 'Step forward media key',
    code: 'KEYCODE_MEDIA_STEP_FORWARD',
  ),
  mediaStop(label: 'Stop media key', code: 'KEYCODE_MEDIA_STOP'),
  charsetSwitch(
    label: 'Switch Charset modifier key',
    code: 'KEYCODE_SWITCH_CHARSET',
  ),
  symbol(label: 'Symbol modifier key', code: 'KEYCODE_SYM'),
  systemNavigationDown(
    label: 'System Navigation Down key',
    code: 'KEYCODE_SYSTEM_NAVIGATION_DOWN',
  ),
  systemNavigationLeft(
    label: 'System Navigation Left key',
    code: 'KEYCODE_SYSTEM_NAVIGATION_LEFT',
  ),
  systemNavigationRight(
    label: 'System Navigation Right key',
    code: 'KEYCODE_SYSTEM_NAVIGATION_RIGHT',
  ),
  systemNavigationUp(
    label: 'System Navigation Up key',
    code: 'KEYCODE_SYSTEM_NAVIGATION_UP',
  ),
  systemRequest(
    label: 'System Request / Print Screen key',
    code: 'KEYCODE_SYSRQ',
  ),
  letterT(label: 'T key', code: 'KEYCODE_T'),
  tab(label: 'Tab key', code: 'KEYCODE_TAB'),
  tvTeletext(label: 'Teletext key', code: 'KEYCODE_TV_TELETEXT'),
  thumbsDown(label: 'Thumbs down key', code: 'KEYCODE_THUMBS_DOWN'),
  thumbsUp(label: 'Thumbs up key', code: 'KEYCODE_THUMBS_UP'),
  tvTimerProgramming(
    label: 'Timer programming key',
    code: 'KEYCODE_TV_TIMER_PROGRAMMING',
  ),
  captions(label: 'Toggle captions key', code: 'KEYCODE_CAPTIONS'),
  tvNetwork(label: 'Toggle Network key', code: 'KEYCODE_TV_NETWORK'),
  tv(label: 'TV key', code: 'KEYCODE_TV'),
  tvDataServce(label: 'TV data service key', code: 'KEYCODE_TV_DATA_SERVICE'),
  tvInput(label: 'TV input key', code: 'KEYCODE_TV_INPUT'),
  tvPower(label: 'TV power key', code: 'KEYCODE_TV_POWER'),
  letterU(label: 'U key', code: 'KEYCODE_U'),
  unknown(label: 'Unknown key code', code: 'KEYCODE_UNKNOWN'),
  letterV(label: 'V key', code: 'KEYCODE_V'),
  tvInputVga1(label: 'VGA #1 key', code: 'KEYCODE_TV_INPUT_VGA_1'),
  voiceAssist(label: 'Voice Assist key', code: 'KEYCODE_VOICE_ASSIST'),
  volumeDown(label: 'Volume Down key', code: 'KEYCODE_VOLUME_DOWN'),
  volumeMute(label: 'Volume Mute key', code: 'KEYCODE_VOLUME_MUTE'),
  volumeUp(label: 'Volume Up key', code: 'KEYCODE_VOLUME_UP'),
  letterW(label: 'W key', code: 'KEYCODE_W'),
  wakeup(label: 'Wakeup key', code: 'KEYCODE_WAKEUP'),
  window(label: 'Window key', code: 'KEYCODE_WINDOW'),
  letterX(label: 'X key', code: 'KEYCODE_X'),
  buttonX(label: 'X Button key', code: 'KEYCODE_BUTTON_X'),
  letterY(label: 'Y key', code: 'KEYCODE_Y'),
  buttonY(label: 'Y Button key', code: 'KEYCODE_BUTTON_Y'),
  programmableYellow(
    label: 'Yellow \'programmable\' key',
    code: 'KEYCODE_PROG_YELLOW',
  ),
  letterZ(label: 'Z key', code: 'KEYCODE_Z'),
  buttonZ(label: 'Z Button key', code: 'KEYCODE_BUTTON_Z'),
  zoomIn(label: 'Zoom in key', code: 'KEYCODE_ZOOM_IN'),
  tvZoomMode(label: 'Zoom mode key', code: 'KEYCODE_TV_ZOOM_MODE'),
  zoomOut(label: 'Zoom out key', code: 'KEYCODE_ZOOM_OUT'),
  charApostrophe(label: '\' key', code: 'KEYCODE_APOSTROPHE'),
  charAt(label: '@ key', code: 'KEYCODE_AT'),
  charBackslash(label: '\\ key', code: 'KEYCODE_BACKSLASH'),
  charComma(label: ', key', code: 'KEYCODE_COMMA'),
  charEquals(label: '= key', code: 'KEYCODE_EQUALS'),
  charGrave(label: '` key', code: 'KEYCODE_GRAVE'),
  charBracketLeft(label: '[ key', code: 'KEYCODE_LEFT_BRACKET'),
  charMinus(label: '- key', code: 'KEYCODE_MINUS'),
  charPeriod(label: '. key', code: 'KEYCODE_PERIOD'),
  charPlus(label: '+ key', code: 'KEYCODE_PLUS'),
  charPound(label: '# key', code: 'KEYCODE_POUND'),
  charBracketRight(label: '] key', code: 'KEYCODE_RIGHT_BRACKET'),
  charSemicolon(label: '; key', code: 'KEYCODE_SEMICOLON'),
  charSlash(label: '/ key', code: 'KEYCODE_SLASH'),
  charStar(label: '* key', code: 'KEYCODE_STAR');

  final String label;
  final String code;

  const KeyCode({required this.label, required this.code});
}
